// react/todoapp/src/components/TodoList.js
import React from 'react';
import { useState } from 'react';
import Button from 'react-bootstrap/Button';

function TodoList(props){
    const [title, settitle] = useState("Title");
    const [desc, setdesc] = useState("Description");
    console.log(title);
    console.log(desc);
    return(
        <div className='py-5'>
            <div className='container'>
                <h2 className='mb-4'>Toto List Component. - {props.title}</h2>
                <form id="todo" onSubmit={(e)=>{props.test(e)}}>
                    <div>
                        <label className='me-2'>Title : </label>
                        <input type="text" name="title" id="title" placeholder="Enter Todo Title" onChange={(e)=>{settitle(e.target.value);}} />
                    </div>
                    <br />
                    <div>
                        <label className='me-2'>Description : </label>
                        <input type="text" name="desc" id="desc" placeholder="Enter Todo Description" onChange={(e)=>{setdesc(e.target.value);}} />
                    </div>
                    <br />
                    <Button type="submit" variant="primary">Submit</Button>{' '}
                </form>
            </div>
        </div>
    )
}
export default TodoList;

// vue/todo-app/src/components/TodoList.vue
<template>
    <section class="todolist-section">
        <div class="container">
            <h2>This is Todo List</h2>
            <form action="#" method="get" v-on:submit="consoleNow()">
                <label for="title">
                    Title :
                </label>
                <br/>
                <input type="text" id="title" placeholder="Enter Title" required v-model="title"/>
                <br/>
                <br/>
                <label for="desc">
                    Description :
                </label>
                <br/>
                <textarea row="10" cols="30" id="desc" placeholder="Enter Description" v-model="desc"></textarea>
                <br/>
                <br/>
                <button type="submit">Submit</button>
            </form>
        </div>
    </section>
</template>
<script>
export default {
    name: "TodoList",
    data(){
        return{
            name: "santosh kumar",
            email: "santosh@carzso.com",
            title: null,
            desc: null,
            todoList: [{
                title:null,
                desc:null
            }]
        }
    },
    methods: {
        consoleNow(){
            
            event.preventDefault();
            console.log("Title : ", this.title);
            console.log("Desc : ",this.desc);
        }
    },
}
</script>
<style scoped>
    .todolist-section{
        padding: 100px 0;
        height: 50vh;
    }
    .todolist-section h2{
        margin-bottom: 15px;
    }
    .todolist-section h2,
    .todolist-section form{
        text-align: left;
    }
</style>
